### PR TITLE
Update JS dependencies; mention yarn in INSTALL.md

### PR DESCRIPTION
**Pull request by clarfon**
Was having trouble getting this to build on the latest version of node.js, so I decided to update the dependencies in package.json. I haven't actually verified these work exactly the same re: functionality, but it appeared that most of the out-of-date ones were gulp-related, and I knew how to fix those.

One particularly notable change is that uglifyjs has been forked into terser, and `gulp-terser` was used instead of `gulp-uglify`. In terms of the restructuring of the gulpfile, Gulp 4 gets rid of the dependency resolution in favour of the functions `gulp.series` and `gulp.parallel`. Instead of passing each individual function to a task, they were named as variables and the individual tasks had their dependencies manually listed via these build methods.

Additionally, I added a note in `INSTALL.md` that you need to install with `yarn` instead of `npm`, as the Makefile itself uses yarn.

### CODE REVIEW

**Comment by vbatoufflet** [comment]
Hi @clarfon,

Indeed, the build dependencies are completely outdated, and to be fully honest as the next version of Facette I am preparing will ditch Javascript, Angular and gulp in favor of TypeScript, Vue.js and Webpack, I didn't took the time to update them.

In any case, thanks for the PR! I'll take a look to see if everything goes well with those changes before merging it, and let you know.

**Comment by clarfon** [comment]
Done and rebased! Let me know if you want anything else changed. :)

**Comment by vbatoufflet** [comment]
LGTM 👍

Thanks again for your PR!

**Comment by clarfon** [comment]
Thank you for the merge!

How soon do you think you're going to get those reworked changes done? Would you be willing to make a 0.5.1 release so I can update the Arch Linux package without any external patches?

No rush, of course, and thank you for the awesome work. :)

**Comment by vbatoufflet** [comment]
Ongoing work on the next version will still take me quite time.

I'll prepare a 0.5.1 in the meantime :)

**Comment by vbatoufflet** [comment]
@clarfon, I just released the [0.5.1](https://github.com/facette/facette/releases/tag/0.5.1) version. This version includes your changes :)

**Pull request merged**
