### PR TITLE
add connector for KairosDB provider

### PR DESCRIPTION
**Pull request by iaean**
This is replacement for PR #153.

### CODE REVIEW

**Comment by iaean** [comment]
Hi @falzm, @vbatoufflet,
I closed #153 and opened this one as suggested by Marc. If this doesn't help, tell me how I can achieve your requirements without losing my fork. IMHO all changes are combined in commit '05067a1'.

**Comment by falzm** [comment]
Hi @iaean 

Thank you, we'll take it from here. Could you provide us with an email address, since we'll squash the commits ourselves and add and "Author" field to keep you credited? Also, you can add an entry in the `AUTHOR` file along with the other contributors :)

Thank you.

**Comment by iaean** [comment]
Hi @falzm,

thanks for the contributors hint.
I did it and created PR #163 additionally, hoping it's matching your initial requirement, now.
I'll send you an E-Mail off-site regarding my address. So you can decide what PR you like more.

Thanks for your patience.
I'm always excited to hear from you.
Best regards

**Comment by vbatoufflet** [comment]
I clase this PR as it had been handled in #163.

**Pull request closed without merging**
